services:
  nginx:
    build: ./nginx
    ports:
    - 8080:80
    - 444:443
    networks:
      - dev-network
  mysql: 
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - dev-network
  nextjs:
    build: ./nextjs
    volumes:
      - ./nextjs/src:/app/nextjs/src
    networks:
      - dev-network
    command: npm run dev
networks:
  dev-network:
    driver: bridge
