services:
  nginx:
    build: ./nginx
    ports:
    - 8080:80
    - 4443:443
    networks:
      - dev-network
  nextjs:
    build: ./nextjs
    volumes:
      - ./nextjs/src:/app/nextjs/src
      - ./nextjs/public:/app/nextjs/public
    networks:
      - dev-network
    command: npm run dev
networks:
  dev-network:
    driver: bridge
