services:
  nginx:
    build: ./nginx
    ports:
    - 80:80
    - 443:443
    networks:
      - dev-network
  mysql: 
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - dev-network
  nodejs:
    build: ./nodejs
networks:
  dev-network:
    driver: bridge
